- generic [ref=e2]:
  - generic [ref=e3]:
    - heading "🏗️ Cal AI — 아키텍처 시각화" [level=1] [ref=e4]
    - button "🌓 테마 전환" [ref=e6] [cursor=pointer]
  - generic [ref=e7]:
    - button "1. 시스템 아키텍처" [active] [ref=e8] [cursor=pointer]
    - button "2. 화면 흐름" [ref=e9] [cursor=pointer]
    - button "3. 모듈 의존성" [ref=e10] [cursor=pointer]
    - button "4. 음식 분석 흐름" [ref=e11] [cursor=pointer]
    - button "5. 인증 흐름" [ref=e12] [cursor=pointer]
    - button "6. AI 에이전트 파이프라인" [ref=e13] [cursor=pointer]
  - generic [ref=e15]:
    - document [ref=e17]:
      - generic [ref=e19]:
        - generic [ref=e20]:
          - generic [ref=e25]: 💾 로컬 스토리지
          - generic [ref=e30]: 🌐 외부 서비스
          - generic [ref=e35]: ☁️ 백엔드 API
          - generic [ref=e40]: 🖥️ 클라이언트 계층
        - generic [ref=e49]:
          - generic [ref=e53]: HTTP
          - generic [ref=e57]: HTTP
          - generic [ref=e61]: HTTP
          - generic [ref=e65]: 반환
          - generic [ref=e69]: 호출
          - generic [ref=e73]: 프록시
          - generic [ref=e77]: 저장
          - generic [ref=e81]: 저장
          - generic [ref=e85]: 등록
          - generic [ref=e89]: 캐싱
        - generic [ref=e90]:
          - generic [ref=e96]:
            - text: localStorage
            - text: (설정, 토큰, 캐시)
          - generic [ref=e102]:
            - text: IndexedDB
            - text: (오프라인 데이터)
          - generic [ref=e108]:
            - text: 🔐 Supabase
            - text: (Auth + PostgreSQL)
          - generic [ref=e114]:
            - text: 🤖 Google Gemini
            - text: (Vision API)
          - generic [ref=e120]:
            - text: 📊 식약처 식품 DB
            - text: (영양성분 검색)
          - generic [ref=e126]:
            - text: GET /api/config
            - text: (환경변수 프록시)
          - generic [ref=e132]:
            - text: POST /api/analyze
            - text: (이미지 분석)
          - generic [ref=e138]:
            - text: GET /api/food-search
            - text: (음식 DB 프록시)
          - generic [ref=e144]:
            - text: 📱 브라우저
            - text: (단일 HTML SPA)
          - generic [ref=e150]:
            - text: ⚙️ Service Worker
            - text: (PWA 캐싱)
    - generic [ref=e151]:
      - heading "시스템 아키텍처" [level=3] [ref=e152]
      - paragraph [ref=e153]: 칼로리 트래커의 전체 구조를 보여줍니다. 단일 HTML SPA가 Vercel Edge Functions을 통해 외부 서비스와 통신합니다.
      - list [ref=e154]:
        - listitem [ref=e155]:
          - strong [ref=e156]: 클라이언트 계층
          - text: ": 모든 코드가 output/index.html 파일 하나에 포함된 SPA"
        - listitem [ref=e157]:
          - strong [ref=e158]: 백엔드 API
          - text: ": 3개의 Vercel Edge Function (config, analyze, food-search)"
        - listitem [ref=e159]:
          - strong [ref=e160]: 외부 서비스
          - text: ": Supabase (인증/DB), Gemini API (AI 분석), 공공 식품 DB"
        - listitem [ref=e161]:
          - strong [ref=e162]: 로컬 스토리지
          - text: ": API 키, 사용자 설정, 임시 캐시 저장"
      - generic [ref=e163]:
        - generic [ref=e164]: 클라이언트
        - generic [ref=e166]: 백엔드
        - generic [ref=e168]: 외부 서비스
  - generic [ref=e170]:
    - paragraph [ref=e171]: Cal AI Architecture Documentation
    - paragraph [ref=e172]: Generated on 2026-05-26 | Framework-agnostic Design
    - paragraph [ref=e173]: 다이어그램을 마우스로 드래그하면 이동하고 휠로 확대/축소할 수 있습니다.